### PR TITLE
Save space in final docker image 

### PR DESCRIPTION
**Pull request by orlandine**
Uses multistage build to discard installation artifacts prior to finalization.

### CODE REVIEW

**Comment by orlandine** [comment]
Btw, docker build should be run with --squash option.

**Comment by monda07** [comment]
A couple observations:
The Docker documentation still listed --squash as an experimental feature.  As such I don't think it is appropriate to refer to yet as a standard practice.  Someone familiar with these features would already know about squash and wouldn't need it in the official documentation.  Plus, you have to specifically enable experimental features.  That's fine for knowledgable people.

I have experimental turned on and using squash resulted in no improvement in storage use.
actian/vector5.0    squash              d4b70f67b3f6        2 hours ago         1.94GB
actian/vector5.0    community           11932dd51fa9        3 hours ago         1.94GB

**Comment by orlandine** [comment]
Agree on the experimental state of --squash. Background:

- Docker Desktop CE 2.0.0.2
- actian-vector-5.1.0-103-community-linux-x86_64-UpgradePatch10304

vector:community   1.99GB <= default
vector:multistage   2.9GB <= not good :)
vector:squash   1.55GB <= squash makes sense with multistage build

**Comment by monda07** [comment]
Docker still has squash marked as experimental.  As a result we will leave it to the developer to decide if squash is necessary.

**Pull request closed without merging**
